# Copyright 2012, Qualcomm Innovation Center, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

import os
Import('env')

# OpenWRT specific vars
vars = Variables()
vars.Add('TARGET_PATH', 'Paths to toolchain for cross compiling AllJoyn for OpenWRT', os.environ.get('TARGET_PATH'))
vars.Add('TARGET_CC', 'OpenWRT C compiler', os.environ.get('TARGET_CC'))
vars.Add('TARGET_CFLAGS', 'OpenWRT C compiler flags', os.environ.get('TARGET_CFLAGS'))
vars.Add('TARGET_CPPFLAGS', 'OpenWRT C pre-processor compiler flags', os.environ.get('TARGET_CPPFLAGS'))

vars.Add('TARGET_CXX', 'OpenWRT C++ compiler', os.environ.get('TARGET_CXX'))

vars.Add('TARGET_LINK', 'OpenWRT Linker', os.environ.get('TARGET_CC')) # Normally use the C compiler for linking.
vars.Add('TARGET_LINKFLAGS', 'OpenWRT Linker flags', os.environ.get('TARGET_LDFLAGS'))

vars.Add('STAGING_DIR', 'OpenWRT staging dir', os.environ.get('STAGING_DIR'))

vars.Update(env)
Help(vars.GenerateHelpText(env))

# Get the compiler flags OpenWrt requires.
flags = env.ParseFlags(' '.join([env['TARGET_CFLAGS'], env['TARGET_CPPFLAGS'], env['TARGET_LINKFLAGS']]))

# Put OpenWrt build paths in environment varaibles so GCC will search those
# paths after paths specified with -I and -L.
env['ENV']['CPATH']=':'.join(flags['CPPPATH'])
env['ENV']['LIBRARY_PATH']=':'.join(flags['LIBPATH'])

# Clear out the CPPPATH and LIBPATH values so that we can merge the rest of
# the flags with the SCons build environment.
flags['CPPPATH'] = []
flags['LIBPATH'] = []

# Merge the rest of the compiler flags
env.MergeFlags(flags)

# Set compiler and linker commands.
env.Replace(CC = env['TARGET_CC'])
env.Replace(CXX = env['TARGET_CXX'])
env.Replace(LINK = env['TARGET_LINK'])

env['ENV']['PATH'] = env['TARGET_PATH']
env['ENV']['STAGING_DIR'] = env['STAGING_DIR']

# Set Project and platform flags.
env.Append(CPPFLAGS=['-Wno-deprecated'])  # AllJoyn uses various deprecated template classes (i.e., hash_map)
env.Append(CXXFLAGS=['-std=c++0x',
                     '-fno-exceptions'])
env.Append(CPPDEFINES=['QCC_OS_LINUX'])
env.Append(LIBS=['m'])  # STL needs libm on OpenWrt
